# Generated by Django 4.2.1 on 2023-05-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computerscienceeducatorspost',
            options={'ordering': ['stack_exchange_id']},
        ),
        migrations.AlterModelOptions(
            name='cseendeavour',
            options={'ordering': ['value']},
        ),
        migrations.RenameField(
            model_name='cseendeavour',
            old_name='label',
            new_name='value',
        ),
    ]
